name: Run Tests For Pull Request

on: 
  pull_request:
    branches: [ master ]
    
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker Image
        run: docker build -t stephengrider/docker-react -f Dockerfile.dev .
      - name: Run tests with the image
        run: docker run stephengrider/docker-react npm run test
