name: Run Tests and Deploy

on:
  push:
    branches: [ master ] 
    
    
jobs:
  testanddeploy:
    runs-on: ubutnu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build a test docker image
        run: docker build -t stephengrider/docker-react -f Dockerfile.dev .
      - name: Run tests with the image
        run: docker run -e CI=true stephengrider/docker-react npm run test
